name: Ava / Tests

on: [push]

jobs:
  check:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests via avajs/ava
        run: npm run test:ci > test-results.xml
      - name: Publish test results
        uses: enricomi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: test-results.xml
